import React from 'react';
import { motion } from 'framer-motion';
import { CheckCircle, AlertTriangle, XCircle, Download, ArrowLeft, Zap, TrendingUp, Target } from 'lucide-react';
import { RadialBarChart, RadialBar, ResponsiveContainer, PolarAngleAxis } from 'recharts';
import { AnalysisResult } from '../types';

interface AnalysisResultsProps {
  results: AnalysisResult;
  onReset: () => void;
}

const AnalysisResults: React.FC<AnalysisResultsProps> = ({ results, onReset }) => {
  
  const getScoreColor = (score: number) => {
    if (score >= 80) return '#10b981'; // Emerald
    if (score >= 60) return '#f59e0b'; // Amber
    return '#ef4444'; // Red
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 }
  };

  // Data for Radial Chart
  const chartData = [
    { name: 'Standout', value: results.standoutScore, fill: '#8b5cf6' },
    { name: 'ATS Match', value: results.atsMatchScore, fill: '#3b82f6' },
    { name: 'Skills', value: results.skillRelevanceScore, fill: '#06b6d4' }
  ];

  return (
    <div className="min-h-screen bg-slate-950 pb-20 px-4 md:px-8">
      {/* Header */}
      <header className="py-8 flex justify-between items-center max-w-7xl mx-auto border-b border-slate-800 mb-8">
        <div className="flex items-center gap-4">
          <button onClick={onReset} className="p-2 rounded-full hover:bg-slate-800 text-slate-400 transition">
            <ArrowLeft size={24} />
          </button>
          <div>
            <h2 className="text-2xl font-bold text-white">Evaluation Report</h2>
            <p className="text-sm text-slate-400">Generated by ResumeAI Evaluator</p>
          </div>
        </div>
        <button className="hidden md:flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-sm font-medium transition">
          <Download size={16} />
          Export PDF
        </button>
      </header>

      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="show"
        className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-3 gap-8"
      >
        {/* Left Column: Scores & Quick Stats */}
        <div className="space-y-8">
          <motion.div variants={itemVariants} className="glass-panel p-6 rounded-2xl">
            <h3 className="text-lg font-semibold mb-6 flex items-center gap-2">
              <TrendingUp className="text-violet-400" size={20} /> Overall Impact
            </h3>
            <div className="h-64 w-full relative">
              <ResponsiveContainer width="100%" height="100%">
                <RadialBarChart 
                  innerRadius="30%" 
                  outerRadius="100%" 
                  data={chartData} 
                  startAngle={90} 
                  endAngle={-270}
                >
                  <RadialBar
                    background
                    dataKey="value"
                    cornerRadius={10}
                    label={false}
                  />
                  <text x="50%" y="45%" textAnchor="middle" dominantBaseline="middle" className="fill-white text-3xl font-bold">
                    {Math.round((results.standoutScore + results.atsMatchScore + results.skillRelevanceScore) / 3)}
                  </text>
                  <text x="50%" y="55%" textAnchor="middle" dominantBaseline="middle" className="fill-slate-400 text-xs">
                    AVG SCORE
                  </text>
                </RadialBarChart>
              </ResponsiveContainer>
              {/* Legend */}
              <div className="flex justify-around mt-4 text-xs font-medium">
                <div className="flex items-center gap-1"><span className="w-3 h-3 rounded-full bg-violet-500"></span> Standout</div>
                <div className="flex items-center gap-1"><span className="w-3 h-3 rounded-full bg-blue-500"></span> ATS</div>
                <div className="flex items-center gap-1"><span className="w-3 h-3 rounded-full bg-cyan-500"></span> Skills</div>
              </div>
            </div>
          </motion.div>

          <motion.div variants={itemVariants} className="glass-panel p-6 rounded-2xl">
            <h3 className="text-lg font-semibold mb-4">Executive Summary</h3>
            <p className="text-slate-300 text-sm leading-relaxed">{results.summary}</p>
          </motion.div>

          <motion.div variants={itemVariants} className="glass-panel p-6 rounded-2xl">
            <h3 className="text-lg font-semibold mb-4 text-green-400 flex items-center gap-2">
               <Zap size={18}/> Key Strengths
            </h3>
            <ul className="space-y-3">
              {results.strengths.map((item, idx) => (
                <li key={idx} className="flex items-start gap-3 text-sm text-slate-300">
                  <CheckCircle className="text-green-500 shrink-0 mt-0.5" size={16} />
                  {item}
                </li>
              ))}
            </ul>
          </motion.div>
        </div>

        {/* Middle Column: Detailed Analysis */}
        <div className="lg:col-span-2 space-y-8">
          
          {/* ATS & Weaknesses */}
          <motion.div variants={itemVariants} className="grid md:grid-cols-2 gap-6">
             <div className="glass-panel p-6 rounded-2xl border-l-4 border-red-500">
               <h3 className="text-lg font-semibold mb-4 text-red-400 flex items-center gap-2">
                 <AlertTriangle size={18}/> Critical Weaknesses
               </h3>
               <ul className="space-y-3">
                {results.weaknesses.map((item, idx) => (
                  <li key={idx} className="flex items-start gap-3 text-sm text-slate-300">
                    <XCircle className="text-red-500 shrink-0 mt-0.5" size={16} />
                    {item}
                  </li>
                ))}
              </ul>
             </div>

             <div className="glass-panel p-6 rounded-2xl border-l-4 border-blue-500">
               <h3 className="text-lg font-semibold mb-4 text-blue-400 flex items-center gap-2">
                 <Target size={18}/> ATS Compatibility
               </h3>
               <div className="space-y-2 mb-4">
                 <div className="flex justify-between text-xs text-slate-400">
                   <span>Keyword Match</span>
                   <span>{results.atsMatchScore}%</span>
                 </div>
                 <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                   <div className="h-full bg-blue-500" style={{ width: `${results.atsMatchScore}%` }}></div>
                 </div>
               </div>
               <div className="flex flex-wrap gap-2">
                 {results.missingSkills.slice(0, 4).map((skill, idx) => (
                   <span key={idx} className="px-2 py-1 bg-red-500/10 text-red-400 text-xs rounded border border-red-500/20">
                     Missing: {skill}
                   </span>
                 ))}
               </div>
             </div>
          </motion.div>

          {/* Section Breakdown */}
          <motion.div variants={itemVariants} className="glass-panel p-6 rounded-2xl">
            <h3 className="text-xl font-semibold mb-6">Section-by-Section Breakdown</h3>
            <div className="space-y-4">
              {results.sectionAnalysis.map((section, idx) => (
                <div key={idx} className="bg-slate-800/40 rounded-xl p-4 border border-slate-700/50">
                  <div className="flex justify-between items-center mb-2">
                    <h4 className="font-medium text-slate-200">{section.sectionName}</h4>
                    <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                      section.status === 'Excellent' ? 'bg-green-500/20 text-green-400' :
                      section.status === 'Good' ? 'bg-blue-500/20 text-blue-400' :
                      section.status === 'Needs Improvement' ? 'bg-orange-500/20 text-orange-400' :
                      'bg-red-500/20 text-red-400'
                    }`}>
                      {section.status}
                    </span>
                  </div>
                  <p className="text-sm text-slate-400">{section.feedback}</p>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Rewrites */}
          {results.rewrittenSamples.length > 0 && (
             <motion.div variants={itemVariants} className="glass-panel p-6 rounded-2xl bg-gradient-to-br from-violet-900/20 to-slate-900">
               <h3 className="text-xl font-semibold mb-6 flex items-center gap-2">
                 <SparklesIcon className="text-violet-400" /> AI Rewrites
               </h3>
               <div className="space-y-6">
                 {results.rewrittenSamples.map((sample, idx) => (
                   <div key={idx} className="grid md:grid-cols-2 gap-4 bg-black/20 p-4 rounded-xl">
                     <div className="space-y-2">
                       <span className="text-xs uppercase tracking-wider text-red-400 font-bold">Original (Concept)</span>
                       <p className="text-sm text-slate-500 italic">"{sample.original}"</p>
                     </div>
                     <div className="space-y-2">
                       <span className="text-xs uppercase tracking-wider text-green-400 font-bold">AI Improved</span>
                       <p className="text-sm text-slate-200">{sample.improved}</p>
                       <p className="text-xs text-violet-400 mt-2 border-t border-white/5 pt-2">Why: {sample.reasoning}</p>
                     </div>
                   </div>
                 ))}
               </div>
             </motion.div>
          )}

        </div>
      </motion.div>
      
      <footer className="mt-12 text-center">
         <p className="text-slate-600 text-sm font-mono">Made by CARL BENEDICT ELIPAN</p>
      </footer>
    </div>
  );
};

const SparklesIcon = ({ className }: { className?: string }) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className={`w-6 h-6 ${className}`}>
    <path fillRule="evenodd" d="M9 4.5a.75.75 0 01.721.544l.813 2.846a3.75 3.75 0 002.576 2.576l2.846.813a.75.75 0 010 1.442l-2.846.813a3.75 3.75 0 00-2.576 2.576l-.813 2.846a.75.75 0 01-1.442 0l-.813-2.846a3.75 3.75 0 00-2.576-2.576l-2.846-.813a.75.75 0 010-1.442l2.846-.813a3.75 3.75 0 002.576-2.576l.813-2.846A.75.75 0 019 4.5zM9 15a.75.75 0 01.75.75v1.5h1.5a.75.75 0 010 1.5h-1.5v1.5a.75.75 0 01-1.5 0v-1.5h-1.5a.75.75 0 010-1.5h1.5v-1.5A.75.75 0 019 15z" clipRule="evenodd" />
  </svg>
);

export default AnalysisResults;